---
title: "Reimagining Cultural Heritage in the Digital Age, A Journey Through Research"
subtitle: "Professorial Innagural"
output: powerpoint_presentation
bibliography: allpubs.bib
---
  
::: {.notes}
As our lives become increasingly digital, so too does our experience of culture. Advances in computing are transforming artefacts, historic environments, and cultural practices into interactive digital experiences. These "digital twins" do more than preserve the past — they make heritage accessible beyond physical museums and archives, opening up new possibilities for creativity, education, and public engagement.


::::

# Topics

## - Context and bias
## - A quest for data
## - Data-driven approaches
## - Role of Artificial Intelligence
## - Metrics and Impact

:::: notes
This talk traces the motivations, questions, and continuous evolution of my research, as well as the wider research landscape on digital innovation. Through digital innovation, my research aims to uncover the
stories of material culture and the people, both past and present,
who created and interacted with these objects and environments.
Their narratives, and what they tell us about being human, are a constant focus of the research.

The talk is organised across three main topics, each aligned with a decade of research. I will begin by outlining my background and context. Next, I will trace the motivations, questions, and evolution of my research, as well as the wider research landscape on digital innovation.

Secondly, I will explore the big push for digitisation in the 2000s, particularly across the Galleries, Libraries, Archives and Museums (or GLAM) sectors.

Following this, I will discuss the infrastructures and data-driven approaches developed to organise, enable, and open access to data.

I would finish with the rise of Artificial Intelligence and explore its role in trawling large amounts of data.

Through these sections, the talk explores how digital technologies, especially visual technologies, have transformed how we document and preserve culture. They have also changed who can access it, how we engage with it, and the questions we must ask about ownership, representation, and sustainability.
::::
:::::: {.columns}
::: {.column}
Content of the left column.
:::

::: {.column}
Content of the right column.
:::
::::::
# {background-image="images/Mexico.png"}

:::: notes
Material culture - context
::::

::: {.notes}

::::
<!-- ******************************************************************-->
<!-- ******************************************************************-->
<!-- *******************************Part 1*****************************-->
<!-- *****The quest for data: more data better stories/use*****-->
<!-- ******************************************************************-->
# Post museum

## Audience's experiences
## Interaction between visitor’s contexts (Falk and Dierking 1992):
- Personal
- Social
- Physical

# How can digital technologies contribute to enrich these experiences?

# Digitisation of material culture


# Grand Challenges

## To enhance data capture, preservation and scholarship in cultural heritage
## To bring history to life for the citizen
- Digital reconstruction
- Story telling
- Visitor experiences
- Internet, mobile, digital, virtual reality applications

# 3D scanning

## Records the shape of a real-world object, person or environment. 

# 3D model: digital surrogate

# Workflows for developing interactive experiences
## Digital artefact
## Digital/physical transformations
## Digital artifact
## Physical artifact

# Audiences


# 3D technologies for audiences in a museum gallery
## Physical reconstructions of Sussex ancestors
## Tactile replicas of archaeological artefacts
## Puzzle-based tactile experience

# Immersive Environments

![&copy; [@9b3042bee3474ac1ae615d711196c840]](images/AvatarsEPOCH.png )


<!-- ******************************************************************-->
<!-- ******************************************************************-->
<!-- *******************************Part 2*****************************-->
<!-- **Algorithmic ways to understand/organise data and approaches*******-->
<!-- ******************************************************************-->

# 3D documentation and semantic analysis of architectural heritage 

## Semantic analysis

<!-- ******************************************************************-->
<!-- ******************************************************************-->
<!-- *******************************Part 3*****************************-->
<!-- **Looking at the future: AI role in data-driven approaches*******-->
<!-- ******************************************************************-->

# Acknowledgments

D. Arnold, O. Abdel Barr, A. Aboulfadl, N. Ali, G. Aitken, A. Al-Ashaab, F. Alves de Oliveira, L. Armstrong, X. Aure, J.B. Barreau, E. Bell, N. Brownsword, M. Bushnel, D. Boyer, E. Carillo, W. Cash, M. Chikama, M. Danks, A. Day, A. Delaney, L. Dibble, S. Dixon, M. Doerr, L. Garnier, R. Gaugne, C. Georgis, J. Glauert, M. Goodchild, A. Grantham, M. Griffin, S. Haegler, R. Haynes, M. Hedges, K. Howland, Y. Huang, L. Isaksen, N. Jakeman, V. Jennings, R. Kadobayashi, J. Kaminski, D. Kanellou, E. Kartaki, R. Laycock, Y. Liu, N. Magnenat-Thalmann, R. Marroquim, R. Martin, J. McLoughlin, A. Medeiros, A. Molina, D. Morris, S. Pena Serna, L. Pemberton, M. Penn, M. Proesmans, R. Pillay, D. Pitzalis, S. Sakkout, A. Salah, M. Samaroudi, B. Schneider, R. Scopigno, N. Sharara, S. Shimojo, M. Shepard, E. Silverton, J. Smythe, R. Song, J. Stevenson, A. Stork, Z. Sujon, N. Theophane, M. Theodoridou, A. Trujillo-Vazquez, T. Weyrich, M. Wynne, J. Winchester, J. Winckler, L. Wieneke, L. Yu-Kun, K. Zumkley




:::: notes
I would like to make a special mention of my husband and children, whose unconditional support means more than words can express. 
They provide me with a life beyond research — one that gives everything else its proper meaning and perspective.

# Thank You

## I now introduce name to conclude proceedings Prof Imran Rafiq

::::
# References

::: {#refs}
:::
